CONFIG_ZMK_SLEEP=y

CONFIG_ZMK_EXT_POWER=y

CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=y
CONFIG_ZMK_HID_KEYBOARD_NKRO_EXTENDED_REPORT=y
CONFIG_ZMK_KEYBOARD_NAME="dactyl left"